### ISSUE TITLE
Laravel 5 

### ISSUE THREAD

**Issue by LarryEitel** [AdrianSkierniewski/eloquent-tree#5]
Do you have plans to support Laravel 5?

**Comment by AdrianSkierniewski** [comment]
Yes it works right now in laravel 5 project, but need to do some more tests to check if everything is ok.
[platform](https://github.com/GrupaZero/platform) [cms](https://github.com/GrupaZero/cms)

**Comment by LarryEitel** [comment]
Not realizing that the sample migration was intended to show what fields should be added to an existing migration AND not realizing that I should extend a Model from your Tree abstract, it wasn't working.

So I through the source parts into my app and then it dawned on me how to integrate it properly.

At this point, my initial tests show it to be working in LV 5.

Thank you for sharing your work. :)
