### ISSUE TITLE
Bug Tree::renderRecursiveTree()

### ISSUE THREAD

**Issue by maxnugget** [AdrianSkierniewski/eloquent-tree#7]
In version 2.1 of eloquent-tree in Tree.php, line 511, you have $child->children instead of $child->children(), which in turn is causing Tree:render() to fail to render sub-levels beyodn the first sub-level.

Changing the line to children() appears to fix this issue.

**Comment by AdrianSkierniewski** [comment]
It's probably related to lazy loading. When you're using ->children it should use those already loaded, so it will only work if you build whole tree before use render. Using children() instead should trigger lazy loading on each level manually. We'd need to write some tests to confirm that behavior first and if it's a issue then try to fix this. Unfortunately I don't have any free time now, so fell free to create PR with those tests & fix, so I could review it
